TaskPilot/TaskPilot/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

app_name = "TaskPilot"

TaskPilot/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signup_page/', views.signup_page, name='signup_page'),
    path('login_page/', views.login_page, name='login_page'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

app_name = 'account' 

TaskPilot/boards/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', login_required(views.board_list), name='board_list'),
    path('get_board_content/', views.get_board_content, name='get_board_content'),
    path('board_create/', views.board_create, name='board_create'),
    path('list_create/', views.list_create, name='list_create'),
    path('task_create/', views.task_create, name='task_create'),
    path('update_task/', views.update_task, name='update_task'),
    path('edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('<int:pk>/', views.task_detail, name='task_detail'),
    # URL для оновлення даних про завдання
]

app_name = 'boards'

TaskPilot/accounts/models.py
from django.db import models

# Create your models here.
class Account(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.email

TaskPilot/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from .models import Account

def index(request):
    return render(request, 'accounts/index.html')

def signup_page(request):
    return render(request, 'accounts/signup.html')

def signup(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repeat_password = request.POST.get('repeat_password')
        account = Account.objects.create(
            name=name,
            email=email,
            password=password
        )
        account.save()
        return render(request, 'accounts/login.html')
    return render(request, 'accounts/signup.html')

def login_page(request):
    return render(request, 'accounts/login.html')

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        try:
            account = Account.objects.get(email=email)
            if account.password == password:
                return redirect('boards:board_list')
            else:
                return render(request, 'accounts/login.html', {'error': 'Wrong password'})
        except Account.DoesNotExist:
            return render(request, 'accounts/login.html', {'error': 'Account does not exist'})
    
    return render(request, 'accounts/login.html')

@login_required
def logout(request):
    auth_logout(request)
    return render(request, 'accounts/login.html')

TaskPilot/accounts/templates/accounts/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TaskPilot</title>
    <link rel="stylesheet" href="{% static 'accounts/index.css' %}">
    <link rel="icon" href="{% static 'img/small_logo.svg' %}">
</head>
<body>
    <div class="container">
        <!-- <div class="title">TaskPilot</div> -->
        <img src="{% static 'img/logo.svg' %}" class="logo" alt="Logo">
        <div class="btn_box">
            <a href="{% url 'account:login_page' %}" class="btn">Log In</a>
            <a href="{% url 'account:signup_page' %}" class="btn">Sign Up</a>
        </div>
    </div>
</body>
</html>

TaskPilot/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TaskPilot | Login</title>
    <link rel="stylesheet" href="{% static 'accounts/login.css' %}">
    <link rel="icon" href="{% static 'img/small_logo.svg' %}">
</head>
<body>
    <div class="container">
        <form action="{% url 'account:login' %}" method="post">
            {% csrf_token %}
            <div class="wrap">
                <h1 class="title">Login</h1>
                <div class="data_box">
                    <label for="email"><input class="data_fields" type="email" name="email" placeholder="Email" required></label>
                    <label for="password" class="password_box"><input class="data_fields" type="password" name="password" placeholder="Password" required  minlength="8"><button class="show_pass" type="button"></button></label>
                </div>
                <button class="login_btn" type="submit">Log In</button>
                <a href="{% url 'account:signup_page' %}" class="register_link">Don't have an account? Register</a>
            </div>
        </form>
    </div>
    <script src="{% static 'js/login.js' %}"></script>
</body>
</html>

TaskPilot/accounts/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TaskPilot | Sign Up</title>
    <link rel="stylesheet" href="{% static 'accounts/signup.css' %}">
    <link rel="icon" href="{% static 'img/small_logo.svg' %}">
</head>
<body>
    <div class="container">
        <form action="{% url 'account:signup' %}" method="post">
            {% csrf_token %}
            <div class="wrap">
                <h1 class="title">Sign Up</h1>
                <div class="data_box">
                    <input class="data_fields" type="text" name="name" placeholder="Username" required>
                    <input class="data_fields" type="email" name="email" placeholder="Email" required>
                    <input class="data_fields" type="password" name="password" placeholder="Password" required minlength="8">
                    <input class="data_fields" type="password" name="repeat_password" placeholder="Confirm Password" required minlength="8">
                </div>
                <button class="signup_btn" type="submit">Sign Up</button>
                <a href="{% url 'account:login_page' %}" class="login_link">Already have an account? Log In</a>
            </div>
        </form>
    </div>
</body>
</html>